gitlab-to-pb:
  tags:
    - internal
  image: python:3.6-alpine
  only:
    - triggers
  script:
    - pip install pipenv
    - bash -c "[ -f .venv/bin/python ] || pipenv --python 3.6"
    - pipenv install --deploy
    - pipenv run ./productboard.py productboard update-status --username=$PB_USERNAME --password=$PB_PASSWORD --status "$PB_STATUS" $GL_ISSUES

pb-to-gitlab:
  tags:
    - internal
  image: python:3.6-alpine
  only:
    - manual
  script:
    - pip install pipenv
    - bash -c "[ -f .venv/bin/python ] || pipenv --python 3.6"
    - pipenv install --deploy
    - pipenv run ./productboard.py gitlab sync --username=$PB_USERNAME --password=$PB_PASSWORD --token=$GL_TOKEN --release=$RELEASE
