variables:
  PIPENV_VENV_IN_PROJECT: "1"

stages:
  - build

cache:
  paths:
    - .venv

gitlab-to-pb:
  stage: build
  tags:
    - internal
  image: python:3.6-alpine
  only:
    refs:
      - triggers
      - web
    variables:
      - $PB_STATUS
  script:
    - apk add gcc musl-dev python3-dev libffi-dev openssl-dev
    - pip install pipenv
    - pipenv install --deploy
    - pipenv run ./productboard.py productboard sync --username "$PB_USERNAME" --password "$PB_PASSWORD" --status "$PB_STATUS" $GL_ISSUES
    - pipenv run ./productboard.py zendesk sync --username "$ZD_USERNAME" --password "$ZD_PASSWORD" --token "$GL_TOKEN" --status "$PB_STATUS" $GL_ISSUES

pb-to-gitlab:
  stage: build
  tags:
    - internal
  image: python:3.6-alpine
  only:
    - triggers
  only:
    refs:
      - triggers
      - web
    variables:
      - $RELEASE
      - $IN_PROGRESS

  script:
    - apk add gcc musl-dev python3-dev libffi-dev openssl-dev
    - pip install pipenv
    - pipenv install --deploy
    - pipenv run ./productboard.py gitlab sync --username "$PB_USERNAME" --password "$PB_PASSWORD" --token "$GL_TOKEN" --release "$RELEASE"
