stages:
  - build

gitlab-to-pb:
  stage: build
  tags:
    - internal
  image: python:3.6-alpine
  only:
    - triggers
  script:
    - apk add gcc musl-dev python3-dev libffi-dev openssl-dev
    - pip install pipenv
    - pipenv install --deploy
    - pipenv run ./productboard.py productboard update-status --username=$PB_USERNAME --password=$PB_PASSWORD --status "$PB_STATUS" $GL_ISSUES

pb-to-gitlab:
  stage: build
  tags:
    - internal
  image: python:3.6-alpine
  only:
    - master
  when: manual
  script:
    - apk add gcc musl-dev python3-dev libffi-dev openssl-dev
    - pip install pipenv
    - pipenv install --deploy
    - pipenv run ./productboard.py gitlab sync --username=$PB_USERNAME --password=$PB_PASSWORD --token=$GL_TOKEN --release=$RELEASE
