name: "Sync from github"
description: "Take change from github and notify all other services"
icon: zap
inputs:
  from_ref:
    description: "Starting commit (if not passed, will use from_ref to derive to_ref based on semver)"
    required: false
  to_ref:
    description: "Ending commit"
    required: false
  status:
    description: "Status of the deployement (Staging, Production, Development)"
    default: "Development"
    required: false
  project:
    description: "Path of the project (form of whatever-company/elium-web)"
    required: false
  linear_release:
    description: "true if all release are linear no two versions are released at the same time"
    required: false
  # CREDS
  github-token:
    description: "github token needed for API calls"
    required: true
  slack-url:
    description: "Slack Post URL to post MSG on deploy"
    required: false
  zendesk-username:
    description: "Zendesk username to post MSG on deploy"
    required: false
  zendesk-password:
    description: "Zendesk password to post MSG on deploy"
    required: false
outputs:
  status:
    description: "Log of status"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false

    - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

    - name: Run dev-sync script
      run: uv --directory "${ACTION_PATH}" run --frozen "${ACTION_PATH}/dev-sync.py" from_github to_zendesk to_slack
      shell: bash
      env:
        ACTION_PATH: ${{github.action_path}}
        FROM_REF: ${{ inputs.from_ref }}
        TO_REF: ${{ inputs.to_ref }}
        STATUS: ${{ inputs.status}}
        GH_PROJECT: ${{ inputs.project}}
        LINEAR_RELEASE: ${{ inputs.linear_release}}
        # RELEASE: NOT USED ATM

        # CREDS
        GH_TOKEN: ${{ inputs.github-token}}
        SLACK_URL: ${{ inputs.slack-url}}
        ZD_USERNAME: ${{ inputs.zendesk-username}}
        ZD_PASSWORD: ${{ inputs.zendesk-password}}
