name: "Sync from github"
description: "Take change from github and notify all other services"
icon: zap
inputs:
  from_ref:
    description: "Starting commit (if not passed, will use from_ref to derive to_ref based on semver)"
    required: false
  to_ref:
    description: "Ending commit"
    required: false
  status:
    description: "Status of the deployement (Staging, Production, Development)"
    default: "Development"
    required: false
  project:
    description: "Path of the project (form of whatever-company/elium-web)"
    required: false
  linear_release:
    description: "true if all release are linear no two versions are released at the same time"
    required: false
  # CREDS
  github-token:
    description: "github token needed for API calls"
    required: true
  slack-url:
    description: "Slack Post URL to post MSG on deploy"
    required: false
  zendesk-username:
    description: "Zendesk username to post MSG on deploy"
    required: false
  zendesk-password:
    description: "Zendesk password to post MSG on deploy"
    required: false
outputs:
  status:
    description: "Log of status"
runs:
  using: "composite"
  steps:
    - name: Checkout the repository
      uses: actions/checkout@main
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "0.4.18"
        enable-cache: false

    - name: Run dev-sync script
      run: uv --directory ${{github.action_path}} run --frozen ${{github.action_path}}/dev-sync.py from_github to_zendesk to_slack
      shell: bash
      env:
        FROM_REF: ${{ inputs.from_ref }}
        TO_REF: ${{ inputs.to_ref }}
        STATUS: ${{ inputs.status}}
        GH_PROJECT: ${{ inputs.project}}
        LINEAR_RELEASE: ${{ inputs.linear_release}}
        # RELEASE: NOT USED ATM

        # CREDS
        GH_TOKEN: ${{ inputs.github-token}}
        SLACK_URL: ${{ inputs.slack-url}}
        ZD_USERNAME: ${{ inputs.zendesk-username}}
        ZD_PASSWORD: ${{ inputs.zendesk-password}}
