[tool.poetry]
name = "dev-sync"
version = "0.1.0"
description = "Sync between different tools dev are using (ZenDesk, Slack, Datadog, ...)"
authors = []

[tool.poetry.dependencies]
python = "^3.9"
requests = {extras = ["security"], version = "==2.28.1"}
click = "==8.1.3"
werkzeug = "==2.2.2"
python-dotenv = "==0.21.0"
PyGithub = "==1.57"
semver = "==2.13.0"

[tool.poetry.dev-dependencies]
flake8 = "==6.0.0"
yapf = "==0.32.0"
pylint = "==2.15.8"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
