[tool.poetry]
name = "dev-sync"
version = "0.1.0"
description = "Sync between different tools dev are using (ZenDesk, Slack, Datadog, ...)"
authors = []

[tool.poetry.dependencies]
python = "~3.11"
requests = {extras = ["security"], version = "==2.31.0"}
click = "==8.1.4"
werkzeug = "==2.3.6"
python-dotenv = "==1.0.0"
PyGithub = "==1.58.2"
semver = "==3.0.1"

[tool.poetry.dev-dependencies]
flake8 = "==6.0.0"
black = "==23.7.0"
bandit = "==1.7.5"
flake8-annotations = "==3.0.1"
flake8-bandit = "==4.1.1"
flake8-bugbear = "==23.7.10"
flake8-comprehensions = "==3.13.0"
flake8-logging-format = "0.9.0"
flake8-noqa = "==1.3.2"
flake8-sfs = "==0.0.4"
isort = "==5.12.0"

[tool.black]
line-length = 120
target-version = ['py311']

[tool.isort]
line_length=120
skip_gitignore=true
profile="black"
add_imports=["from __future__ import annotations"]

[tool.pyright]
useLibraryCodeForTypes=true
reportDuplicateImport=true
reportUntypedNamedTuple=true
reportUnnecessaryIsInstance=true
reportUnnecessaryCast=true
reportUnnecessaryComparison=true
reportUnnecessaryTypeIgnoreComment=true
reportImplicitStringConcatenation=true
reportMatchNotExhaustive=true
reportWildcardImportFromLibrary=true
reportConstantRedefinition=true
reportOverlappingOverload=true
reportUnusedClass=true
reportInvalidStubStatement=true
reportIncompleteStub=true
reportUnusedExpression=true
reportCallInDefaultInitializer=true
strictListInference=true
strictSetInference=true
reportMissingParameterType=true
reportUntypedClassDecorator=true
reportUntypedBaseClass=true
reportUnusedFunction=true
reportUntypedFunctionDecorator=true
reportUnusedVariable=true
reportInconsistentConstructor=true
reportMissingTypeArgument=true
reportUnusedImport=true
reportUnnecessaryContains=true
reportShadowedImport=true
reportSelfClsParameterName=true
reportFunctionMemberAccess=true
reportUnknownParameterType=true
strictDictionaryInference=true
reportPrivateUsage=true
reportPropertyTypeMismatch=true
reportImportCycles="information"
reportIncompatibleMethodOverride=true
reportIncompatibleVariableOverride=true
reportUninitializedInstanceVariable=true
reportUnknownLambdaType=true

reportMissingSuperCall=false
reportUnknownArgumentType=false
reportUnknownVariableType=false
reportUnknownMemberType=false

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
