[tool.poetry]
name = "dev-sync"
version = "0.1.0"
description = "Sync between different tools dev are using (productboard, ZenDesk, Slack, ..."
authors = []

[tool.poetry.dependencies]
python = "^3.7"
requests = {extras = ["security"], version = "==2.25.1"}
click = "7.1.2"
werkzeug = "1.0.1"
python-dotenv = "==0.15.0"
PyGithub = "1.54.1"
semver = "==2.13.0"

[tool.poetry.dev-dependencies]
pylint = "==2.7.0"
flake8 = "==3.8.4"
yapf = "0.30.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
