[tool.poetry]
name = "dev-sync"
version = "0.1.0"
description = "Sync between different tools dev are using (ZenDesk, Slack, Datadog, ...)"
authors = []

[tool.poetry.dependencies]
python = "^3.7"
requests = {extras = ["security"], version = "==2.27.1"}
click = "==8.0.4"
werkzeug = "==2.0.3"
python-dotenv = "==0.20.0"
PyGithub = "==1.55"
semver = "==2.13.0"

[tool.poetry.dev-dependencies]
pylint = "==2.12.2"
flake8 = "==4.0.1"
yapf = "==0.32.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
