name: Check deployment

on:
  pull_request: {}

permissions:
  contents: read
  actions: write
  checks: write

jobs:
  sync-deploy:
    name: Sync deployment
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout the repository
        uses: actions/checkout@main
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.18"
          enable-cache: true

      - name: checks ruff
        run: uv run --frozen ruff check .
